export const UNSPLASH_BASE_URL = "https://api.unsplash.com"
const UNSPLASH_ACCESS_KEY = "1GPLMVlbunPJLkVL8CVMF24FBQmMQVA20rbJ4CuW5V4"
//const UNSPLASH_ACCESS_KEY = "jEwEJZbeztRskvUnMfrUi22KExcR6M7mfnxOqubsYuM"

const UNSPLASH_AUTHORIZATION = `Client-ID ${UNSPLASH_ACCESS_KEY}`

export const UNSPLASH_HEADERS = {
    Authorization: UNSPLASH_AUTHORIZATION
}
